# Generated by Django 5.0.6 on 2024-06-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapmaliApp', '0002_order_invoice_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
